services:
  - type: web
    name: credit-risk-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app
    workingDirectory: backend
    autoDeploy: true
